/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Conexion.Listado_Productos;
import Conexion.Producto;
import Conexion.cls_conexion;
import Conexion.id_stock;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class ingreso_producto extends javax.swing.JFrame {

    /**
     * Creates new form ingreso_producto
     */
    public ingreso_producto() {
        initComponents();
        setLocationRelativeTo(null);
        cargarCombo(combo_productos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        combo_productos = new javax.swing.JComboBox<>();
        jtextcantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setForeground(new java.awt.Color(102, 0, 204));
        jLabel1.setText("Producto");

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardarr.png"))); // NOI18N
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salii.png"))); // NOI18N
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(102, 0, 204));
        jLabel2.setText("Cantidad");

        jtextcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtextcantidadKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("INGRESO DE PRODUCTO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtextcantidad, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(combo_productos, javax.swing.GroupLayout.Alignment.LEADING, 0, 152, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnguardar)
                                .addGap(36, 36, 36)
                                .addComponent(btnsalir))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combo_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtextcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar)
                    .addComponent(btnsalir))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        //Oculta esta ventana y vuelve a la ventana "Menu"
        this.setVisible(false);
        Menu ventana = new Menu ();
        ventana.setVisible (true);

        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        //Guarda los datos en la tabla "stock". Verifica si ya hay un registro con el mismo "nombre", si es asi, actualiza el campo
        //"cantidad" sumando los datos que ya estan más los del nuevo registro. Si no hay registro con el mismo "nombre"
        //simplemente se crea un nuevo registro
        cls_conexion mysql= new cls_conexion();
        Connection cn=mysql.getConnection();
        
        String producto = (String) combo_productos.getSelectedItem();
        int cantidad = Integer.parseInt(jtextcantidad.getText());
        int idstock;
        id_stock s =new id_stock();
        idstock= s.id_incrementablestock();
        try{
            String queryVerificar = "SELECT cantidad FROM stock WHERE producto = ?";
            PreparedStatement statementVerificar = cn.prepareStatement(queryVerificar);
            statementVerificar.setString(1, producto);
            
            ResultSet resultSet = statementVerificar.executeQuery();
            
            if (resultSet.next()) {
                // El producto ya existe, se debe actualizar la cantidad
                int cantidadExistente = resultSet.getInt("cantidad");
                int nuevaCantidad = cantidadExistente + cantidad;
                
                String queryActualizar = "UPDATE stock SET cantidad = ? WHERE producto = ?";
                PreparedStatement statementActualizar = cn.prepareStatement(queryActualizar);
                statementActualizar.setInt(1, nuevaCantidad);
                statementActualizar.setString(2, producto);
                
                statementActualizar.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Cantidad actualizada en la tabla 'stock'.","Ingreso", JOptionPane.INFORMATION_MESSAGE);
            } else {
                // El producto no existe, se inserta como un nuevo registro
                String queryInsertar = "INSERT INTO stock (idstock, producto, cantidad) VALUES (?, ?, ?)";
                PreparedStatement statementInsertar = cn.prepareStatement(queryInsertar);
                statementInsertar.setInt(1, idstock);
                statementInsertar.setString(2, producto);
                statementInsertar.setInt(3, cantidad);
                        
                statementInsertar.executeUpdate();
               
                JOptionPane.showMessageDialog(null,"Datos insertados correctamente en la tabla 'stock'.","Ingreso", JOptionPane.INFORMATION_MESSAGE);
               
            }
        }catch(SQLException e){
        
             JOptionPane.showMessageDialog(null,"Error al insertar/actualizar datos en la tabla 'stock': "+e,"Ingreso", JOptionPane.ERROR_MESSAGE);
             
             
        }
        
 //limpiar casillas
        
             
        jtextcantidad.setText("");
         combo_productos.setSelectedIndex(0); //posicion cero es la primera
         
        
        

    }//GEN-LAST:event_btnguardarActionPerformed

    private void jtextcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextcantidadKeyTyped
char numeros=evt.getKeyChar();
    if (Character.isLetter(numeros)) {
        getToolkit().beep();
    
        evt.consume();
    JOptionPane.showMessageDialog(rootPane,"Porfavor ingrese solo numeros");
    }          // TODO add your handling code here:
    }//GEN-LAST:event_jtextcantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingreso_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingreso_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingreso_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingreso_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingreso_producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> combo_productos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtextcantidad;
    // End of variables declaration//GEN-END:variables
    //metodo que permite cargar en un JComboBox los "nombre_productos" de la tabla "productos".
    private void cargarCombo(JComboBox c) {
        cls_conexion con= new cls_conexion();
        Connection cn=con.getConnection();
        DefaultComboBoxModel combo = new DefaultComboBoxModel();
        c.setModel(combo);
        Listado_Productos lp = new Listado_Productos();
        try{
           Statement st=cn.createStatement();
           ResultSet rs=st.executeQuery("SELECT nombre_producto FROM productos");
            while (rs.next()) {                
               Producto pro = new Producto();
               pro.setNom_producto(rs.getString(1));
               lp.AgregarProductos(pro);
               combo.addElement(pro.getNom_producto());
               System.out.println("Exito");
            }
        }catch (Exception e){
            System.out.println("ERROR,NO SE PUEDE MOSTRAR COMBO"+e);
        }
    
    }
}
